---

- include_vars: vars/ports.yml

- set_fact:
    iptables:
      inbound: "{{ ports.inbound }}"

- name: iptables
  include: tasks/iptables.yml

# iptables rules dont include udp/tcp set by libvirt to allow dns for containers
# thus a restart of the lxc-network is necessary

- name: restart lxc network 1/2
  virt_net: command=destroy name=lxc

- name: restart lxc network 2/2
  virt_net: command=start name=lxc

- name: spawn containers
  include: tasks/lxc.yml
  vars:
     container: "{{ hostvars[item] }}"
     container_ip: "{{ hostvars[item]['inventory_hostname'] }}"
  with_items: "{{ groups['container'] }}"
  become: true
  become_user: "{{ container_user }}"

- name: container autostart
  cron: name="lxc-autostart" special_time=reboot job="sleep 30 ; lxc-autostart" user={{ container_user }}