---

- name: spawn containers
  include: tasks/lxc.yml
  vars:
     container: "{{ hostvars[item] }}"
     container_ip: "{{ hostvars[item]['inventory_hostname'] }}"
  with_items: "{{ groups['container'] }}"
  become: true
  become_user: "{{ container_user }}"