---

- include_vars: vars/ports.yml

- set_fact:
    iptables:
      inbound: "{{ ports.inbound }}"

- name: iptables
  include: tasks/iptables.yml

- name: spawn containers
  include: tasks/lxc.yml
  vars:
     container: "{{ hostvars[item] }}"
     container_ip: "{{ hostvars[item]['inventory_hostname'] }}"
  with_items: "{{ groups['container'] }}"
  become: true
  become_user: "{{ container_user }}"

- name: container autostart
  cron: name="lxc-autostart" special_time=reboot job="sleep 30 ; lxc-autostart" user={{ container_user }}