---

- name: install redis
  apt: name={{ item }} state=present
  with_items:
    - redis-server
    - redis-tools

- name: check if munin is installed
  stat:
    path: /usr/share/munin/plugins
  register: munin_installed

- name: deploy redis munin plugin
  copy:
    dest: /usr/share/munin/plugins/redis_
    src: "redis_"
    owner: root
    group: root
    mode: 0755
  when: munin_installed.stat.exists

- name: configure redis servers
  include: tasks/server.yml
  with_items: "{{ redis_servers|default([]) }}"
  loop_control:
    loop_var: "redis"