---

- name: vars required for template vhost.internal.j2
  set_fact:
    asset_access: "css|txt|xml|js|png|gif|jpeg|jpg|woff|woff2|eot|svg|ttf|otf|htm|html"
    files_access: "css|txt|xml|js|png|gif|jpeg|jpg|woff|woff2|eot|svg|ttf|otf|htm|html|doc|docx|xls|xlsx|tiff|zip|gz|tar|bz|bz2|mp3|mp4"

- name: directories
  file: dest={{ item.dir }} state=directory mode=755 owner={{ item.owner }} group={{ item.owner }}
  with_items:
    - dir: /var/www/project
      owner: "{{ deploy_user }}"
    - dir: /var/www/project/files
      owner: www-data
    - dir: /var/www/project/tmp
      owner: www-data
    - dir: /var/www/project/tools
      owner: "{{ deploy_user }}"
    - dir: /var/www/project/tools/cometcache
      owner: "{{ deploy_user }}"
    - dir: /var/www/project/tools/cometcache/cache
      owner: www-data

- name: ribbl cfg
  template: dest=/var/www/project/config.php src=templates/config.php.j2 owner=root group=root mode=0755

- include_vars: vars/sites.yml

- name: ssl settings
  set_fact:
     ssl: "{{ item.ssl }}"
  with_items: "{{ sites }}"
  when: item.target_ip == "{{ ansible_default_ipv4.address }}"

- debug: var=ssl

- name: ribbl vhost
  template: dest=/etc/apache2/sites-available/project.conf src=templates/vhost.conf.j2
  notify:
    - restart apache

- name: enable vhost
  file: src=/etc/apache2/sites-available/project.conf dest=/etc/apache2/sites-enabled/000-project.conf owner=root group=root state=link
  notify:
    - restart apache

