---
- hosts: all
  vars:
     ansible_user: "{{ setup_ansible_user }}"
     ansible_ssh_pass: "{{ setup_ansible_ssh_pass }}"
  tasks:

    - name: Add admin user
      user: name="{{ config_user_name }}" password="{{ config_user_password }}" shell=/bin/bash

    - name: Add authorized keys for admin user
      authorized_key: user="{{ config_user_name }}" key="{{ lookup('file', config_user_public_key_file) }}"
#
#    - name: Add admin user to sudoers
#      lineinfile: dest=/etc/sudoers
#                  regexp="{{ admin_user_name }} ALL"
#                  line="{{ admin_user_name }} ALL=(ALL) ALL"
#                  state=present
#
#    - name: Disallow password authentication
#      lineinfile: dest=/etc/ssh/sshd_config
#                  regexp="^PasswordAuthentication"
#                  line="PasswordAuthentication no"
#                  state=present
#
#    - name: Disallow root SSH access
#      lineinfile: dest=/etc/ssh/sshd_config
#                  regexp="^PermitRootLogin"
#                  line="PermitRootLogin no"
#                  state=present
#
#    - name: Restart ssh
#      command: service ssh restart