---

- name: deploy debmon sources.list
  template: dest=/etc/apt/sources.list.d/debmon.list src=apt.debmon.list.j2

- name: install keys
  apt_key: url={{ item }} state=present
  with_items:
    - "http://debmon.org/debmon/repo.key"

- name: apt update
  apt: update_cache=yes

- name: install icinga
  apt: name={{ item }} state=present
  environment:
    DEBIAN_FRONTEND: noninteractive
  with_items:
    - icinga2
    - icinga2-ido-mysql
    - icingaweb2

- name: check if icinga database is empty (no tables exist yet)
  command: "mysql -h{{ icinga_mysql_host }} -u{{ icinga_mysql_user }} -p{{ icinga_mysql_pass }} {{ icinga_mysql_name }} -e 'show tables;'"
  register: icinga_tables

- name: install icinga schema
  shell: "mysql -h{{ icinga_mysql_host }} -u{{ icinga_mysql_user }} -p{{ icinga_mysql_pass }} {{ icinga_mysql_name }} < /usr/share/icinga2-ido-mysql/schema/mysql.sql"
  when: (icinga_tables.stdout_lines|length == 0)

- name: install icingaweb schema
  shell: "mysql -h{{ icinga_mysql_host }} -u{{ icinga_mysql_user }} -p{{ icinga_mysql_pass }} {{ icinga_mysql_name }} < /usr/share/icingaweb2/etc/schema/mysql.schema.sql"
  when: (icinga_tables.stdout_lines|length == 0)

- name: configure mysql ido
  template: src=ido-mysql.conf.j2 dest=/etc/icinga2/features-available/ido-mysql.conf owner=nagios group=nagios mode=0600
  notify:
    - restart icinga

- name: enable ido mysql
  file: src=/etc/icinga2/features-available/ido-mysql.conf dest=/etc/icinga2/features-enabled/ido-mysql.conf state=link
  notify:
    - restart icinga

- name: apache vhost
  template: dest=/etc/apache2/sites-enabled/icingaweb2.conf src=apache.conf.j2
  notify:
    - restart apache

- name: enable vhost
  file: dest=/etc/apache2/sites-available/icingaweb2.conf src=/etc/apache2/sites-enabled/icingaweb2.conf state=link
  notify:
    - restart apache

# configure icingaweb2

- name: create config dirs
  file: path={{ item }} state=directory owner=root group=www-data mode=0750
  with_items:
    - /etc/icingaweb2
    - /etc/icingaweb2/modules
    - /etc/icingaweb2/modules/monitoring
    - /etc/icingaweb2/enabledModules
- name: create preference dir
  file: path={{ item }} state=directory owner=www-data group=www-data mode=0750
  with_items:
    - /etc/icingaweb2/preferences

- name: deploy config files
  template: dest=/etc/icingaweb2/{{ item }} src="web/{{ item }}.j2" owner=root group=www-data mode=0750
  with_items:
    - authentication.ini
    - config.ini
    - groups.ini
    - resources.ini
    - modules/monitoring/commandtransports.ini
    - modules/monitoring/config.ini

- name: deploy config files (webserver writeable)
  template: dest=/etc/icingaweb2/{{ item }} src="web/{{ item }}.j2" owner=www-data group=www-data mode=0750
  with_items:
    - roles.ini

- name: enable monitoring module
  file: dest=/etc/icingaweb2/enabledModules/monitoring src=/usr/share/icingaweb2/modules/monitoring state=link

- name: create admin user deploy sql-file
  template: src=create_admin.sql.j2 dest=/tmp/icinga_create_admin.sql owner=root group=root mode=0600

- name: create admin user run sql-file
  shell: "mysql -h{{ icinga_mysql_host }} -u{{ icinga_mysql_user }} -p{{ icinga_mysql_pass }} {{ icinga_mysql_name }} < /tmp/icinga_create_admin.sql"

- name: create admin user remove sql-file
  file: path=/tmp/icinga_create_admin.sql state=absent
