---

- name: update sources.list
  template: dest=/etc/apt/sources.list src=templates/apt.sources.list.j2

- name: install keys
  apt_key: url={{ item }} state=present
  with_items: "{{ aptkeys }}"

- name: apt update
  apt: update_cache=yes
