- name: iptables v4 rules template
  template: dest=/etc/iptables/rules.v4.source src="{{ path_ansible_base }}templates/iptables.v4.rules.j2" owner=root group=root mode=0644
  register: iptables_v4_rules
- name: flush iptables v4
  command: iptables -F
  when: iptables_v4_rules.changed
- name: iptables v4 load rules
  command: bash -c "iptables-restore < /etc/iptables/rules.v4.source"
  when: iptables_v4_rules.changed
- name: iptables v4 write back rules
  command: bash -c "iptables-save > /etc/iptables/rules.v4"
  when: iptables_v4_rules.changed

- name: iptables v6 rules template
  template: dest=/etc/iptables/rules.v6.source src="{{ path_ansible_base }}templates/iptables.v6.rules.j2" owner=root group=root mode=0644
  register: iptables_v6_rules
- name: flush iptables v6
  command: ip6tables -F
  when: iptables_v6_rules.changed
- name: iptables v6 load rules
  command: bash -c "ip6tables-restore < /etc/iptables/rules.v6.source"
  when: iptables_v6_rules.changed
- name: iptables v6 write back rules
  command: bash -c "ip6tables-save > /etc/iptables/rules.v6"
  when: iptables_v6_rules.changed
