---

- name: remove default enabled site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - restart apache

- name: include sites
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ path_ansible_local }}vars/sites.yml"
    - "{{ path_ansible_base }}vars/sites.yml"

- name: reverse proxy vhosts
  template: dest=/etc/apache2/sites-available/reverse-{{ item.domain }}.conf src=templates/vhost.conf.j2
  with_items: "{{ sites }}"
  notify:
    - restart apache

- name: enable vhost
  file: src=/etc/apache2/sites-available/reverse-{{ item.domain }}.conf dest=/etc/apache2/sites-enabled/reverse-{{ item.domain }}.conf owner=root group=root state=link
  with_items: "{{ sites }}"
  notify:
    - restart apache
