---

- name: remove default enabled site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - restart apache

- name: include sites
  include_vars: "../../../../vars/sites.yml"

- name: check for each site cert_bot_cert_exists if necessary
  stat: path=/etc/letsencrypt/live/{{ item.domain }}/cert.pem
  with_items: "{{ sites }}"
  register: cert_bot_stats

- name: prep exists list
  set_fact:
    cert_bot_cert_exists: []

- name: populate exists list
  set_fact:
    cert_bot_cert_exists: "{{ cert_bot_cert_exists | union( [ item.item.domain ] ) }}"
  with_items: "{{ cert_bot_stats.results }}"
  when: item.stat.exists

- name: reverse proxy vhosts
  template: dest=/etc/apache2/sites-available/reverse-{{ item.domain }}.conf src=templates/vhost.conf.j2
  with_items: "{{ sites }}"
  notify:
    - restart apache

- name: enable vhost
  file: src=/etc/apache2/sites-available/reverse-{{ item.domain }}.conf dest=/etc/apache2/sites-enabled/reverse-{{ item.domain }}.conf owner=root group=root state=link backup=yes
  with_items: "{{ sites }}"
  notify:
    - restart apache

# prep for certbot

- name: create well-known dir
  file: path=/var/www/html/certbot state=directory owner=root group=root
