---

- include: tasks/packages.yml
- include: tasks/apache.yml

# prepare list of ssl-certs to be deployed

- name: include sites
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ path_ansible_local }}vars/sites.yml"
    - "{{ path_ansible_base }}vars/sites.yml"

- name: build deploy_certs list 1/2
  set_fact:
    deploy_certs_tmp: "{{ deploy_certs_tmp|default([]) | union( [  item.ssl.cert_file|default(false), item.ssl.cert_key_file|default(false), item.ssl.cert_chain_file|default(false), item.ssl.cert_sign_file|default(false)  ] ) }}"
  with_items: "{{ sites }}"

- name: build deploy_certs list 2/2
  set_fact:
    deploy_certs: "{{ deploy_certs_tmp|select()|list }}"

- name: cert dir
  file: path=/etc/ssl-site-certs/ owner=root group=root mode=0755 state=directory

- name: deploy certs
  copy: dest=/etc/ssl-site-certs/{{ item }} src=../../../../local/certs/{{ item }} owner=root group=root mode=0400
  with_items: "{{ deploy_certs }}"
  notify:
    - restart apache