---
- name: set munin vars
  set_fact:
    munin:
      plugins:
        - plugin: apache_accesses
        - plugin: apache_processes
        - plugin: apache_volume
  tags: munin

- include: munin-plugins.yml
  tags: munin
- include: packages.yml
  tags: reverseproxy
- include: apache.yml
  tags: reverseproxy
- include: certs.yml
  tags: reverseproxy
