---

- name: install requirements
  environment:
      DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - apache2-mpm-prefork
    - libapache2-mod-proxy-html
    - openssl
    - ca-certificates

- name: link mpm prefork
  file: src=/etc/apache2/mods-available/{{ item }} dest=/etc/apache2/mods-enabled/{{ item }} state=link
  with_items:
    - mpm_prefork.conf
    - mpm_prefork.load
  notify:
    - restart apache

- name: enable apache modules
  apache2_module: state=present name={{ item }}
  with_items:
    - ssl
    - headers
    - rewrite
    - expires
    - proxy
    - proxy_http
    - cgi
  notify:
    - restart apache
