---

- name: install requirements
  environment:
      DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - apache2-mpm-prefork
    - libapache2-mod-proxy-html
    - openssl
    - ca-certificates

- name: deploy mpm conf
  template: src="mpm_{{ mpm.module }}.conf.j2" dest=/etc/apache2/mods-available/mpm_{{ mpm.module }}.conf

- name: unlink all mpm modules
  file: path=/etc/apache2/mods-enabled/{{ item[0] }}.{{ item[1] }} state=absent
  with_nested:
    - [ "event", "prefork", "worker" ]
    - [ ".conf", ".load" ]
  when: ("{{ mpm.module }}" != item[0])
  notify:
    - restart apache

- name: link preferred mpm module
  file: src=/etc/apache2/mods-available/{{ item }} dest=/etc/apache2/mods-enabled/{{ item }} state=link
  with_items:
    - "mpm_{{ mpm.module }}.conf"
    - "mpm_{{ mpm.module }}.load"
  notify:
    - restart apache

- name: enable apache modules
  apache2_module: state=present name={{ item }}
  with_items:
    - ssl
    - headers
    - rewrite
    - expires
    - proxy
    - proxy_http
    - cgid
  notify:
    - restart apache

- name: enable apache2
  service: name=apache2 enabled=yes