---

- name: install ssmtp
  apt: pkg=ssmtp state=present

- name: ssmtp conf file
  template: src=templates/ssmtp.conf.j2 dest=/etc/ssmtp/ssmtp.conf backup=yes owner=root group=root mode=0644

- name: ssmtp revaliases file
  template: src=templates/revaliases.j2 dest=/etc/ssmtp/revaliases backup=yes owner=root group=root mode=0644
