---

- name: ensure ssmtp is at the latest version
  apt: pkg=ssmtp state=latest

- name: ssmtp conf file
  template: src=templates/ssmtp.conf.j2 dest=/etc/ssmtp/ssmtp.conf backup=yes

- name: ssmtp revaliases file
  template: src=templates/revaliases.j2 dest=/etc/ssmtp/revaliases backup=yes
