---

- name: container run user name and uids
  set_fact:
    container_run_user: "{{ container_user }}-{{ container.hostname }}"

# restart container

- name: stop container
  command: lxc-stop -n {{ container.hostname }}
  args:
    chdir: ~/
  ignore_errors: True

- name: start container
  command: lxc-start -d -n {{ container.hostname }}
  args:
    chdir: ~/