---

- name: container run user name and uids
  set_fact:
    container_run_user: "{{ container_user }}-{{ container.hostname }}"
    uid_begin: "{{ container.userns_offset }}"
    uid_end: "{{ (container.userns_offset+65536)|int }}"

# create container user

- name: create container users
  user: name="{{ container_run_user }}" shell=/bin/bash append=yes

# sub uid/gid

- name: uid for container user
  raw: usermod --add-subuids {{ uid_begin }}-{{ uid_end }} {{ container_run_user }}
- name: gid for container user
  raw: usermod --add-subgids {{ uid_begin }}-{{ uid_end }} {{ container_run_user }}