---

- name: hosts file
  template: dest=/etc/hosts src=hosts.j2

- name: install essentials
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items:
    - inetutils-syslogd
    - iputils-ping
    - logrotate
    - dnsutils
    - telnet
    - cron
    - htop
    - curl
    - wget
    - less
    - nano
    - vim
    - man
    - rsync
    - apt-listchanges

- name: disable loginsuid in pam for cron or crons wont run
  lineinfile: dest=/etc/pam.d/cron regexp="session[\s]+required[\s]+pam_loginuid\.so" line="#session required pam_loginuid.so"
