---

- name: hosts file
  template: dest=/etc/hosts src=hosts.j2

- name: include vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ path_ansible_local }}vars/packages.yml"
    - "{{ path_ansible_base }}vars/packages.yml"

- name: install essentials
  environment:
       DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items: "{{ essentials }}"