---

- name: hosts file
  template: dest=/etc/hosts src=hosts.j2

- name: include vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ path_ansible_local }}vars/packages.yml"
    - "{{ path_ansible_base }}vars/packages.yml"

- name: install essentials
  environment:
       DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items: "{{ essentials }}"

- name: disable loginsuid in pam for cron or crons wont run
  lineinfile: dest=/etc/pam.d/cron regexp="session[\s]+required[\s]+pam_loginuid\.so" line="#session required pam_loginuid.so"