---

- name: hosts file
  template: dest=/etc/hosts src=hosts.j2

- name: include vars
  include_vars: "vars/packages.yml"

- name: install essentials
  environment:
       DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=latest
  with_items: "{{ essentials }}"

- name: include vars
  include_vars: "vars/admins.yml"

- name: prep ssh_config_allow_users
  set_fact:
     ssh_config_allow_users: "{{ admins | map(attribute='name') | join(' ') }}"

- name: create admin
  user: name="{{ item.name }}" password="{{ item.password }}" shell=/bin/bash groups=sudo append=yes
  with_items: "{{ admins }}"

- name: config user authorized key
  authorized_key: user="{{ item.name }}" key="{{ item.ssh_key }}"
  with_items: "{{ admins }}"

- name: create deploy user group
  group: name={{ deploy_user }} gid={{ deploy_user_uid }}
  when: deploy_user is defined

- name: create deploy user
  user: name={{ deploy_user }} group={{ deploy_user }} shell=/bin/bash uid={{ deploy_user_uid }} append=yes
  when: deploy_user is defined

- name: ssh config
  template: dest=/etc/ssh/sshd_config src=sshd_config.j2
  notify:
    - reload sshd