---

- name: spawn containers
  include: tasks/lxc.yml
  vars:
     container_host: "{{ hostvars[item]['inventory_hostname'] }}"
     container_hostname: "{{ hostvars[item]['hostname'] }}"
  with_items: "{{ groups['container'] }}"