---

- name: include vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ path_ansible_local }}vars/admins.yml"
    - "{{ path_ansible_base }}vars/admins.yml"

- name: create admin
  user: name="{{ item.name }}" password="{{ item.password }}" shell=/bin/bash groups=sudo append=yes
  with_items: "{{ admins }}"

- name: admin authorized key
  authorized_key: user="{{ item.0.name }}" key="{{ item.1.key }}"
  with_subelements:
    - "{{ admins }}"
    - ssh_keys

- name: create deploy user
  user: name={{ deploy_user }} shell=/bin/bash append=yes
  when: deploy_user is defined

- name: deploy user authorized key
  authorized_key: user="{{ deploy_user }}" key="{{ deploy_user_key }}"
  when: deploy_user is defined

- name: ssh config
  template: dest=/etc/ssh/sshd_config src=sshd_config.j2
  notify:
    - reload sshd