---

# create container user and ns

- name: spawn containers
  include: tasks/container/lxc.yml
  vars:
     container: "{{ hostvars[container_item] }}"
     container_ip: "{{ hostvars[container_item].public_ip }}"
  with_items: "{{ groups['container'] }}"
  loop_control:
    loop_var: "container_item"
  when: ("{{ limit_container }}" == "") or ("{{ limit_container }}" == "{{ hostvars[container_item].hostname }}" )