---

- name: set vars
  set_fact:
    rotate:
      pattern: "{{ backup_dir }}*.log"
      interval: "daily"
      files: 7

- include: tasks/mysql-server.yml
- include: tasks/backups.yml
- include: tasks/munin.yml
  tags: munin
