---

- name: set vars
  set_fact:
     public_ip: "{{ ansible_default_ipv4.address }}"
     iptables:
       inbound:
         - port: 22
           proto: tcp
         - port: 3306
           proto: tcp
           source: "{{ container_bridge_subnet }}.0/24"
     rotate:
       pattern: "{{ backup_dir }}*.log"
       interval: "daily"
       files: 7

- include: tasks/mysql-server.yml
- include: tasks/backups.yml
- include: ../../../tasks/iptables.yml
