---

- name: set vars
  set_fact:
    munin:
      plugins:
        - plugin: mysql_binlog_groupcommit
          source: github/mysql_
        - plugin: mysql_commands
          source: github/mysql_
        - plugin: mysql_connections
          source: github/mysql_
        - plugin: mysql_files
          source: github/mysql_
        - plugin: mysql_handler_read
          source: github/mysql_
        - plugin: mysql_handler_tmp
          source: github/mysql_
        - plugin: mysql_handler_transaction
          source: github/mysql_
        - plugin: mysql_handler_write
          source: github/mysql_
        - plugin: mysql_innodb_bpool
          source: github/mysql_
        - plugin: mysql_innodb_bpool_act
          source: github/mysql_
        - plugin: mysql_innodb_history_list_length
          source: github/mysql_
        - plugin: mysql_innodb_insert_buf
          source: github/mysql_
        - plugin: mysql_innodb_io
          source: github/mysql_
        - plugin: mysql_innodb_io_pend
          source: github/mysql_
        - plugin: mysql_innodb_log
          source: github/mysql_
        - plugin: mysql_innodb_queries
          source: github/mysql_
        - plugin: mysql_innodb_read_views
          source: github/mysql_
        - plugin: mysql_innodb_rows
          source: github/mysql_
        - plugin: mysql_innodb_semaphores
          source: github/mysql_
        - plugin: mysql_innodb_srv_master_thread
          source: github/mysql_
        - plugin: mysql_innodb_tnx
          source: github/mysql_
        - plugin: mysql_max_mem
          source: github/mysql_
        - plugin: mysql_mrr
          source: github/mysql_
        - plugin: mysql_myisam_indexes
          source: github/mysql_
        - plugin: mysql_network_traffic
          source: github/mysql_
        - plugin: mysql_performance
          source: github/mysql_
        - plugin: mysql_qcache
          source: github/mysql_
        - plugin: mysql_qcache_mem
          source: github/mysql_
        - plugin: mysql_select_types
          source: github/mysql_
        - plugin: mysql_slow
          source: github/mysql_
        - plugin: mysql_sorts
          source: github/mysql_
        - plugin: mysql_table_definitions
          source: github/mysql_
        - plugin: mysql_table_locks
          source: github/mysql_
        - plugin: mysql_tables
          source: github/mysql_
        - plugin: mysql_tmp_tables
          source: github/mysql_
        - plugin: mysql_bytes
          source: github/mysql_bytes
        - plugin: mysql_queries
          source: github/mysql_queries

- name: install munin plugins dependencies
  apt: name={{ item }} state=present
  with_items:
   - libdbi-perl
   - libdbd-mysql-perl
   - libcache-perl
   - libcache-cache-perl

- name: create custom plugin dir
  file: dest=/usr/share/munin/plugins/github state=directory mode=0755 owner=root group=root

- name: "deploy plugins (source: github)"
  copy: src=files/munin/{{ item }} dest=/usr/share/munin/plugins/github/{{ item }} mode=0755 owner=root group=root
  with_items:
    - mysql_
    - mysql_bytes
    - mysql_innodb
    - mysql_isam_space_
    - mysql_queries
    - mysql_slowqueries
    - mysql_threads

- name: activate plugins
  file: src=/usr/share/munin/plugins/{{ item.source|default(item.plugin) }} dest=/etc/munin/plugins/{{ item.plugin }} state=link owner=root group=root
  with_items: "{{ munin.plugins }}"
  notify:
    - restart munin