---

- name: install mysql-server
  apt: name={{ item }} state=latest default_release=jessie-backports
  with_items:
  - python
  - python-mysqldb
  - mysql-server-5.6

- name: my.cnf
  template: dest=/etc/mysql/mysql.conf.d/mysqld.cnf src=my.cnf.j2 backup=yes
  notify:
   - restart mysql

- name: enable mysql
  service: name=mysql enabled=yes