---

- name: set vars
  set_fact:
     public_ip: "{{ ansible_default_ipv4.address }}"
     iptables:
       inbound:
         - port: 22
           proto: tcp
         - port: 8080
           proto: tcp
           source: "{{ container_bridge_subnet }}.1/32"

- include: tasks/iptables.yml