---

- name: include vars
  include_vars: "vars/admins.yml"

- name: create admin
  user: name="{{ item.name }}" password="{{ item.password }}" shell=/bin/bash groups=sudo append=yes
  with_items: "{{ admins }}"

- name: config user authorized key
  authorized_key: user="{{ item.name }}" key="{{ item.ssh_key }}"
  with_items: "{{ admins }}"

- name: prep ssh_config_allow_users
  set_fact:
     ssh_config_allow_users: "{{ container_user }} {{ admins | map(attribute='name') | join(' ') }}"

- name: allow users in ssh
  template: dest=/etc/ssh/sshd_config src=shared/sshd_config.j2 owner=root group=root mode=0644

- name: reload ssh
  command: systemctl reload ssh.service
