---

- name: install requirements
  apt: name={{ item }} update_cache=yes state=present
  with_items:
  - python
  - python-libvirt
  - python-lxml
  - libvirt-bin

- name: create libvirt network hook
  template: dest=/etc/libvirt/hooks/network src="{{ path_ansible_base }}templates/libvirt-hook-network.j2" mode=0755
  when: iptables.forward is defined

- name: define network
  virt_net: command=define name=lxc xml='{{ lookup("template", "bridge/bridge.xml.j2") }}'

- name: gather facts
  virt_net: command=facts

- name: start network
  virt_net: command=create name=lxc
  when: ansible_libvirt_networks.lxc.state != "active"

- name: ensure network active at boot
  virt_net: autostart=yes name=lxc
  when: ansible_libvirt_networks.lxc.autostart != "yes"