---

- name: include vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ path_ansible_local }}vars/packages.yml"
    - "{{ path_ansible_base }}vars/packages.yml"

- name: install basics 1/2
  apt: name={{ item }} state=present
  with_items: "{{ essentials }}"

- name: install basics 2/2
  apt: name={{ item }} state=present
  with_items: "{{ essentials_master }}"

- name: mysql-client
  apt: name=mysql-client state=present

- name: restart ntp
  service: name=ntp state=restarted enabled=yes