---

- name: apt/sources.list
  template: dest=/etc/apt/sources.list src=../../../templates/apt.sources.list.j2

- name: upgrade system
  apt: upgrade=dist update_cache=yes

- name: install basics
  apt: name={{ item }} update_cache=yes state=present
  with_items:
  - sudo
  - iptables-persistent
  - fail2ban
  - cgroup-tools
  - uidmap
  - ntp

- name: restart ntp
  service: name=ntp state=restarted enabled=yes