---

- name: apt/sources.list
  template: dest=/etc/apt/sources.list src=../../../templates/apt.sources.list.j2

- name: upgrade system
  apt: upgrade=dist update_cache=yes

- name: install basics
  apt: name={{ item }} state=present
  with_items:
  - sudo
  - iptables-persistent
  - fail2ban
  - uidmap
  - ntp

- name: linux kernel upgrade
  apt: name=linux-image-amd64 state=present default_release=jessie-backports

- name: restart ntp
  service: name=ntp state=restarted enabled=yes