---

- name: deploy munin opcache plugin 1/2
  copy: src=files/munin/php_opcache dest=/usr/share/munin/plugins/php_opcache mode=0755 owner="root" group="root"
  notify:
    - restart munin

- name: deploy munin opcache plugin 2/2
  copy: src=files/munin/php_opcache.php dest=/var/www/html/php_opcache.php mode=0644 owner="root" group="root"
  notify:
    - restart munin

- name: link opcache plugin
  file: src=/usr/share/munin/plugins/php_opcache dest=/etc/munin/plugins/php_opcache state=link owner=root group=root
  notify:
    - restart munin