---

- name: install requirements
  environment:
      DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items:
    - libapache2-mod-php5
    - php5
    - php5-curl
    - php5-mcrypt
    - php5-mysql
    - php5-readline
    - php5-imap
    - php5-gd
    - php5-json
  notify:
    - restart apache