---

- name: set vars
  set_fact:
     aptsources:
       - "deb http://packages.dotdeb.org jessie all"
       - "deb-src http://packages.dotdeb.org jessie all"
     aptkeys:
       - "https://www.dotdeb.org/dotdeb.gpg"

- name: update sources.list
  template: dest=/etc/apt/sources.list src=../../../templates/apt.sources.list.j2

- name: install keys
  apt_key: url={{ item }} state=present
  with_items: "{{ aptkeys }}"

- name: apt update
  apt: update_cache=yes

- include: tasks/packages.yml
- name: php-logdir
  file: path=/var/log/php state=directory owner=www-data group=www-data mode=0755

- name: php ini
  template: dest=/etc/php/7.0/{{ item }}/php.ini src=templates/php.{{ item }}.ini.j2 backup=yes
  with_items:
    - "apache2"
    - "cli"
  notify:
   - restart apache

- name: enable php7.0
  apache2_module: state=present name=php7.0
  notify:
   - restart apache
