---

- name: deploy dotdeb sources.list
  template: dest=/etc/apt/sources.list.d/dotdeb.list src=apt.dotdeb.list.j2

- name: install keys
  apt_key: url={{ item }} state=present
  with_items:
    - "https://www.dotdeb.org/dotdeb.gpg"

- name: apt update
  apt: update_cache=yes

- include: tasks/packages.yml
- name: php-logdir
  file: path=/var/log/php state=directory owner=www-data group=www-data mode=0755

- name: php ini
  template: dest=/etc/php/7.0/{{ item }}/php.ini src=templates/php.{{ item }}.ini.j2 backup=yes
  with_items:
    - "apache2"
    - "cli"
  notify:
   - restart apache

- name: logrotate for php logs
  template: dest=/etc/logrotate.d/php src=templates/php.logrotate.j2

- name: enable php7.0
  apache2_module: state=present name=php7.0
  notify:
   - restart apache
