---

- name: install requirements
  environment:
      DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=latest
  with_items:
    - libapache2-mod-php7.0
    - php7.0
    - php7.0-cli
    - php7.0-common
    - php7.0-curl
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-readline
    - php7.0-imap
    - php7.0-imagick
    - php7.0-json
    - php7.0-xml
    - php7.0-mbstring