---

- name: install requirements
  environment:
      DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items:
    - "libapache2-mod-php{{ php_version }}"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-readline"
    - "php{{ php_version }}-imap"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-imagick"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-intl"
  notify:
    - restart apache