---

- name: install requirements
  environment:
      DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items:
    - libapache2-mod-php
    - php7.0-curl
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-readline
    - php7.0-imap
    - php7.0-gd
    - php7.0-imagick
    - php7.0-json
    - php7.0-xml
    - php7.0-mbstring
    - php7.0-intl
  notify:
    - restart apache