---

- name: Set timezone variables
  copy: content='{{ timezone }}'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  register: timezone_changed

- name: dpkg reconfigure
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: timezone_changed.changed