---

- name: apt/sources.list
  template: dest=/etc/apt/sources.list src=apt.sources.list.j2

- name: upgrade system
  apt: upgrade=dist update_cache=yes

- name: install basics
  apt: name={{ item }} state=present
  with_items:
  - sudo
  - iptables-persistent
  - fail2ban
  - uidmap
  - ntp

- name: stop fail2ban for now
  service: name=fail2ban state=stopped

- name: linux kernel upgrade
  apt: name=linux-image-amd64 state=latest default_release=jessie-backports

- name: include vars
  include_vars: "../../../../vars/packages.yml"

- name: install basics 1/2
  apt: name={{ item }} state=present
  with_items: "{{ essentials }}"

- name: install basics 2/2
  apt: name={{ item }} state=present
  with_items: "{{ essentials_master }}"