---

- name: apt/sources.list
  template: dest=/etc/apt/sources.list src=apt.sources.list.j2

- name: upgrade system
  apt: upgrade=dist update_cache=yes

- name: install basics
  apt: name={{ item }} state=present
  with_items:
  - sudo
  - iptables-persistent
  - fail2ban
  - uidmap
  - ntp

- name: stop fail2ban for now
  service: name=fail2ban state=stopped

- name: linux kernel upgrade
  apt: name=linux-image-amd64 state=latest default_release=jessie-backports

- name: install essentials
  environment:
    DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items:
    - iptables-persistent
    - inetutils-syslogd
    - iputils-ping
    - logrotate
    - iptables
    - dnsutils
    - telnet
    - cron
    - htop
    - curl
    - wget
    - less
    - nano
    - vim
    - man
