---

- name: create config user
  user: name="{{ config_user_name }}" password="{{ config_user_password_encrypted }}" shell=/bin/bash groups=sudo append=yes

- name: config user authorized key
  authorized_key: user="{{ config_user_name }}" key="{{ config_user_public_key }}"

- name: include vars
  include_vars: "../../vars/admins.yml"

- name: create admins
  user: name="{{ item.name }}" password="{{ item.password_encrypted }}" shell=/bin/bash groups=sudo append=yes
  with_items: "{{ admins }}"

- name: admin authorized key
  authorized_key: user="{{ item[0].name }}" key="{{ item[1].key }}"
  with_subelements:
    - "{{ admins }}"
    - ssh_keys

- name: sshd config
  template: dest=/etc/ssh/sshd_config src=../../../templates/sshd_config.j2 owner=root group=root mode=0644