---

- name: set vars
  set_fact:
    munin:
      plugins:
        - plugin: apache_accesses # machine specific
        - plugin: apache_processes
        - plugin: apache_volume
        - plugin: http_loadtime
  tags: munin

- name: activate plugins
  file: src=/usr/share/munin/plugins/{{ item.source|default(item.plugin) }} dest=/etc/munin/plugins/{{ item.plugin }} state=link owner=root group=root
  with_items: "{{ munin.plugins }}"
  notify:
    - restart munin
  tags: munin

- include: tasks/packages.yml
- include: tasks/apache.yml