---

- name: set vars
  set_fact:
     public_ip: "{{ ansible_default_ipv4.address }}"
     iptables:
       inbound:
         - port: 80
           proto: tcp
           source: "{{ container_bridge_subnet }}.0/24"
         - port: 443
           proto: tcp
           source: "{{ container_bridge_subnet }}.0/24"

- include: tasks/packages.yml
- include: tasks/iptables.yml
- include: tasks/apache.yml