---

- name: install requirements
  environment:
      DEBIAN_FRONTEND: noninteractive
  apt: name={{ item }} state=present
  with_items:
    - mysql-client
    - apache2
    - apache2-mpm-prefork
    - openssl
    - ca-certificates

- name: deploy mpm conf
  template: src="mpm_{{ mpm.module }}.conf.j2" dest=/etc/apache2/mods-available/mpm_{{ mpm.module }}.conf

- name: unlink all mpm modules
  file: path=/etc/apache2/mods-enabled/mpm_{{ item[0] }}.{{ item[1] }} state=absent
  with_nested:
    - ["event","worker","prefork"]
    - ["conf","load"]
  when: ("{{ mpm.module }}" != item[0])
  notify:
    - restart apache

- name: link preferred mpm module
  file: src=/etc/apache2/mods-available/{{ item }} dest=/etc/apache2/mods-enabled/{{ item }} state=link
  with_items:
    - "mpm_{{ mpm.module }}.conf"
    - "mpm_{{ mpm.module }}.load"
  notify:
    - restart apache

- name: install precompiled mod_rpaf 0.8.4 from https://github.com/gnif/mod_rpaf
  copy:
    src: files/mod_rpaf.so
    dest: /usr/lib/apache2/modules/mod_rpaf.so
    owner: root
    group: root
    mode: 0644

- name: rpaf configs
  template: src=templates/rpaf.{{ item }}.j2 dest=/etc/apache2/mods-available/mod_rpaf.{{ item }}
  with_items:
    - "load"
    - "conf"
  notify:
    - restart apache

- name: enable module rpaf
  file: src=/etc/apache2/mods-available/mod_rpaf.{{ item }} dest=/etc/apache2/mods-enabled/mod_rpaf.{{ item }} state=link
  with_items:
    - "load"
    - "conf"
  notify:
    - restart apache

- name: apache modules
  apache2_module: state=present name={{ item }}
  with_items:
    - headers
    - rewrite
    - expires
  notify:
    - restart apache

- name: enable apache
  service: name=apache2 enabled=yes