---

- name: set vars
  set_fact:
    munin:
      plugins:
        - plugin: netstat
        - plugin: fw_forwarded_local
        - plugin: fw_packets
        - plugin: fw_conntrack
        - plugin: "if_{{ public_eth }}"
          source: if_
        - plugin: "if_err_{{ public_eth }}"
          source: if_err_
        - plugin: ntp_kernel_pll_freq
        - plugin: ntp_kernel_pll_off
        - plugin: ntp_kernel_err
        - plugin: ntp_offset
        - plugin: entropy
        - plugin: interrupts
        - plugin: irqstats
        - plugin: open_files
        - plugin: df
        - plugin: df_inode
        - plugin: diskstats
        - plugin: open_inodes
        - plugin: cpu
        - plugin: forks
        - plugin: swap
        - plugin: memory
        - plugin: munin_stats
        - plugin: load
        - plugin: threads
        - plugin: proc_pri
        - plugin: processes
        - plugin: users
        - plugin: uptime
        - plugin: vmstat

- name: install packages
  apt: name=munin state=present
  register: munin_node_installed

- name: install packages
  apt: name={{ item }} state=latest
  with_items:
    - munin
    - python-passlib

- name: create directory for basic auth files
  file: path=/etc/apache2/basic-auth state=directory

- name: create password file for basic auth
  htpasswd: path=/etc/apache2/basic-auth/munin name={{ munin_user }} password={{ munin_pass }} owner=root group=www-data mode=0640

- name: enable cgi module
  apache2_module: state=present name=cgi
  notify:
    - restart apache

- name: disable default apache conf
  file: path=/etc/apache2/conf-enabled/munin.conf state=absent
  notify:
    - reload apache

- name: deploy apache munin site .conf
  template: src={{ item }} dest=/etc/apache2/sites-available/munin.conf
  with_first_found:
    - "{{ path_ansible_local }}templates/munin.conf.j2"
    - "{{ path_ansible_base }}roles/munin/templates/munin.conf.j2"
  notify:
    - reload apache

- name: enable apache munin site .conf
  file: src=/etc/apache2/sites-available/munin.conf dest=/etc/apache2/sites-enabled/munin.conf state=link
  notify:
    - reload apache

- name: remove all (default) plugins
  shell: rm -f /etc/munin/plugins/*
  when: munin_node_installed.changed

- include: ../../../tasks/munin-plugins.yml