---

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - munin
    - python-passlib
    - libwww-perl
  register: munin_node_installed

- name: create directory for basic auth files
  file: path=/etc/apache2/basic-auth state=directory

- name: create password file for basic auth
  htpasswd: path=/etc/apache2/basic-auth/munin name={{ munin_user }} password={{ munin_pass }} owner=root group=www-data mode=0640

- name: disable default apache conf
  file: path=/etc/apache2/conf-enabled/munin.conf state=absent
  notify:
    - reload apache

- name: enable cgid module
  apache2_module: state=present name=cgid
  notify:
    - restart apache

- name: deploy apache munin site .conf
  template: src={{ item }} dest=/etc/apache2/sites-available/munin.conf
  with_first_found:
    - "{{ path_ansible_local }}templates/apache.conf.j2"
    - "{{ path_ansible_base }}roles/munin/templates/apache.conf.j2"
  notify:
    - reload apache

- name: enable apache munin site .conf
  file: src=/etc/apache2/sites-available/munin.conf dest=/etc/apache2/sites-enabled/munin.conf state=link
  notify:
    - reload apache

- name: munin-node.conf
  template: src=munin.conf.j2 dest=/etc/munin/munin.conf owner=root group=root
  notify:
    - restart munin

- name: disable loginsuid in pam for cron or munin-cron wont run
  lineinfile: dest=/etc/pam.d/cron regexp="session[\s]+required[\s]+pam_loginuid\.so" line="#session required pam_loginuid.so"