---

- hosts: container
  vars:
    ansible_user: "{{ config_user_name }}"
    ansible_become_pass: "{{ config_user_password }}"
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - debug: msg=""

- hosts: master
  vars:
    ansible_user: "{{ config_user_name }}"
    ansible_become_pass: "{{ config_user_password }}"
  become: true
  become_user: root
  become_method: sudo

  vars_prompt:
    - name: "confirm_destroy"
      prompt: "are you sure? if so please type 'yes'"
      private: no
    - name: "destroy_container"
      prompt: "which container should be removed?"
      private: no

  tasks:
    - name: check confirm
      fail: msg="you did not confirm, aborting"
      when: (confirm_destroy != "yes")

    - name: check that container exists
      stat: path="/var/lib/lxc/{{ destroy_container }}"
      register: container_exists

    - name: fail if not
      fail: msg="container {{ destroy_container }} does not exist"
      when: container_exists.stat.exists == False

    - name: force shutdown container
      shell: "lxc-stop -k -n {{ destroy_container }}"

    - name: destroy container
      shell: "lxc-destroy -n {{ destroy_container }}"