---

- hosts: all
  vars:
    ansible_user: "{{ config_user_name }}"
    ansible_become_pass: "{{ config_user_password }}"
  become: true
  become_user: root
  become_method: sudo

  vars_prompt:
    - name: "service"
      prompt: "which service should be restarted?"
      private: no

  tasks:
    - name: restart service
      service: name={{ service }} state=restarted