---

- hosts: all
  vars:
    ansible_user: "{{ config_user_name }}"
    ansible_become_pass: "{{ config_user_password }}"
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: upgrade packages
      environment:
        DEBIAN_FRONTEND: noninteractive
        ES_SKIP_SET_KERNEL_PARAMETERS: "true"
      apt:
        upgrade: dist
        update_cache: yes