---
- hosts: master
  vars:
    ansible_user: "{{ config_user_name }}"
    ansible_become_pass: "{{ config_user_password_clear }}"
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: munin
      tags: munin
    - role: apticron
      tags: apticron
    - role: ssmtp
      tags: ssmtp
    - role: reverseproxy