---

# gather facts about containers

- hosts: container
  vars:
    ansible_user: "{{ config_user_name }}"
    ansible_become_pass: "{{ config_user_password }}"
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - debug: msg="do nothing"

- hosts: master
  vars:
    ansible_user: "{{ config_user_name }}"
    ansible_become_pass: "{{ config_user_password }}"
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: munin
      tags: munin
    - role: reverseproxy
      tags: reverseproxy
    - role: apticron
      tags: apticron
    - role: ssmtp
      tags: ssmtp
    - role: timezone
      tags: timezone
    - role: certbot
      tags: certbot