---

- hosts: master
  vars:
    ansible_user: "{{ config_user_name }}"
    ansible_become_pass: "{{ config_user_password }}"
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: users
      tags: users
    - role: iptables
      tags: iptables
    - role: munin-node
      tags: munin
    - role: reverseproxy
      tags: reverseproxy
    - role: apticron
      tags: apticron
    - role: apt-monitor
      tags: apt-monitor
    - role: ssmtp
      tags: ssmtp
    - role: timezone
      tags: timezone
    - role: certbot
      tags: certbot
